export const COLUMN_LABELS: Record<string, string> = {
  id: 'ID',
  first_name: 'Имя',
  last_name: 'Фамилия',
  middle_name: 'Отчество',
  passport_data: 'Паспорт',
  phone_number: 'Телефон',
  individual_id: 'Физическое лицо',
  contract_number: 'Номер трудового договора',
  position: 'Должность',
  hire_date: 'Дата приёма',
  login: 'Логин',
  password_hash: 'Пароль (хэш)',
  email: 'Электронная почта',
  balance: 'Баланс',
  client_id: 'Клиент',
  address_id: 'Адрес',
  employee_id: 'Сотрудник',
  monthly_payment_amount: 'Ежемесячный платёж',
  file_link: 'Ссылка на файл',
  duration: 'Срок (мес.)',
  sign_date: 'Дата подписания',
  contract_id: 'Договор',
  date: 'Дата',
  region: 'Регион',
  city: 'Город',
  street: 'Улица',
  building: 'Дом',
  apartment: 'Квартира',
  coffee_machine_id: 'Кофемашина',
  status_change_date: 'Дата смены статуса',
  work_status: 'Статус работы',
  model_id: 'Модель',
  brand_id: 'Бренд',
  type_id: 'Тип',
  pressure: 'Давление',
  power: 'Мощность',
  water_tank_volume: 'Объём бака',
  cups_per_hour: 'Чашек/час',
  bean_container_volume: 'Объём зёрен',
  chip_number: 'Номер чипа',
  width: 'Ширина',
  height: 'Высота',
  depth: 'Глубина',
  weight: 'Вес',
  name: 'Название',
  photo_link: 'Ссылка на фото',
  change_date: 'Дата изменения',
  price: 'Цена',
  drink_id: 'Напиток',
}

export function columnLabel(columnName: string): string {
  return COLUMN_LABELS[columnName] ?? columnName
}
